### ISSUE TITLE
PKGBUILD cannot work, missing source.

### ISSUE THREAD

**Issue by zvyn** [ZaneA/WacomWebPlugin#11]
The PKGBUILD is broken since the archive-folder is gone. You could just do the three steps from the README in the build-section.

``` bash
git clone git@github.com:ZaneA/WacomWebPlugin.git
cd src/src/
make
install [file].so /path/to/mozilla/libs/[file.so]
```

Best regards,
Milan

**Comment by ZaneA** [comment]
Hi zvynar,

Thanks for your feedback.

Could you elaborate on how the PKGBUILD is broken? I just tried it out straight from AUR and it's building perfectly for me.

Cheers,
Zane

**Comment by zvyn** [comment]
Seemed to be a temporary problem, I was able to install it now. I still do not understand, why I get a 404-error on https://github.com/ZaneA/WacomWebPlugin/archive/ while https://github.com/ZaneA/WacomWebPlugin/archive/v0.3.0.tar.gz exists.

However, the PKGBUILD works again.

Thanks for your development,
Milan

**Comment by ZaneA** [comment]
Ah I see :)

Well I'm glad it is working now, I hope the plugin does its job for you!

Cheers,
Zane
